### ISSUE TITLE
TODOS

### ISSUE THREAD

**Issue by yhancsx** [yhancsx/yhancsx-next#5]
#### Common
- [x] post, project, publicastion 타입 정의
- [ ] 폰트 정하기
- [x] 일단 PC모드 완성하고 -> 반응형 정리
- [ ] github action 배포 (gh-pages ?)
- [ ] 데이터 옮기기
- [ ] 메인 자기소개 문구 생각하기
  - I'm interested in boosting customer experience with interactions and animations.
  - I love to use typescript, React/Vue, D3.js, SVG, WebGL.
  - Currently Front-end Engineer at Naver Corporation

#### Home
- [x] 유튜브, 인스타 링크
- [ ]

#### Posts
- [x] PostPreivew > description  필수작정하는걸로
- [ ] default thumbnail 이미지

#### Projects
- [ ] Project Preview 카드형 만들기
  - [x] 한행에 3개 / 모바일은 1개
  - [ ] 컨텐츠: 
      - [vue option](https://github.com/yhancsx/prettier-plugin-vue-component-options) -> [badge 붙이기](https://docs.github.com/en/actions/deployment/about-deployments/deploying-with-github-actions#displaying-a-status-badge) 
      - https://yhancsx.github.io/html-css-svg-animations/ ?
 - [x] detail은 없음. 링크만 연결

#### Publications
